In [2]:
%pip install nbformat
%pip install plotly
%pip install numpy

In [3]:
import plotly.express as px
import plotly.graph_objects as go

import pandas as pd
import numpy as np

<ipython-input-3-c65f21c74bcb>:4: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [4]:
pd.set_option("display.max_columns",None)

<h1>Scatter Plot with Graph Object</h1>

In [5]:
age = np.random.randint(25,55,60)
income = np.random.randint(300000,700000,3000000)

In [1]:
fig = go.Figure()
##3fig

<class 'NameError'>: name 'go' is not defined

In [2]:
#fig.add_trace(go.Scatter(x = age, y = income, mode = "markers", marker = dict(color="red"))) 
fig.update_layout(title= "Economical Survey", xaxis_title= "age", yaxis_title = "income")

<class 'NameError'>: name 'fig' is not defined

<h1>Line  with Graph Object</h1>

In [8]:
sells_data=[50,100,40,150,160,70,60,45]
months=["Jan","Feb","Mar","April","May","June","July","August"]

In [3]:
#fig = go.Figure()
fig.add_trace(go.Scatter(x = months, y = sells_data, mode = "lines", marker = dict(color = "green")))
fig.update_layout(title="Bycycle sells per month", xaxis_title="Months", yaxis_title = "number of sells")

<class 'NameError'>: name 'fig' is not defined

<h1>Bar Plot  with Express</h1>

In [10]:
grades=[80,90,56,88,95]

level=['Grade 6','Grade 7','Grade 8','Grade 9','Grade 10']

In [4]:
#fig = px.bar(x = level, y = grades, title = "Grade Average per School Level")
fig.update_layout(xaxis_title= "School level", yaxis_title = "Grades (/100)")

<class 'NameError'>: name 'fig' is not defined

<h1>Histogram with Express</h1>

In [12]:
height = np.random.normal(160,11,300)

In [5]:
fig= px.histogram(x = height, title ="Distribution of height for 200 persons")
fig.update_layout(xaxis_title = "height")
#fig.show()

<class 'NameError'>: name 'px' is not defined

<h1>Bubble Plot with Express</h1>

In [14]:
crime_details = {
    'City' : ['Chicago', 'Chicago', 'Austin', 'Austin','Seattle','Seattle', "San Francisco"],
    'Numberofcrimes' : [1000, 1200, 400, 700,350,1500, 5000],
    'Year' : ['2007', '2008', '2007', '2008','2007','2008', "2008"],
}

In [15]:
df = pd.DataFrame(crime_details)
df.head()

      City  Numberofcrimes  Year
0  Chicago            1000  2007
1  Chicago            1200  2008
2   Austin             400  2007
3   Austin             700  2008
4  Seattle             350  2007

In [16]:
group_data = df.groupby(by = "City")["Numberofcrimes"].sum().reset_index()
group_data

            City  Numberofcrimes
0         Austin            1100
1        Chicago            2200
2  San Francisco            5000
3        Seattle            1850

In [6]:
fig = px.scatter(group_data, x = "City", y = "Numberofcrimes", size = "Numberofcrimes",hover_name = "City",title = "Number of Crime per City", size_max = 30)
#fig.show()

<class 'NameError'>: name 'px' is not defined

<h1>Pie Chart</h1>

In [18]:
spending_percent= [20, 50, 10,8,12]
categories = ['Grocery', 'Rent', 'School Fees','Transport','Savings']

In [7]:
fig = px.pie(values = spending_percent, names = categories, title = "Proportion of Expenditure")
#fig.show()

<class 'NameError'>: name 'px' is not defined

<h1>Radial Chart</h1>

In [20]:
data = dict(
    character=["Eve", "Cain", "Seth", "Enos", "Noam", "Abel", "Awan", "Enoch", "Azura"],
    parent=["", "Eve", "Eve", "Seth", "Seth", "Eve", "Eve", "Awan", "Eve" ],
    value=[10, 14, 12, 10, 2, 6, 6, 4, 4])

In [8]:
fig = px.sunburst(data, names = "character", parents = "parent", values = "value", title = "Radial Chart for Family Structure")
#fig.show()

<class 'NameError'>: name 'px' is not defined

<h1>Airline Data Set</h1>

In [22]:
import requests

def download(url, filename):
    response  = requests.get(url)
    try: 
        if response.status_code == 200:
            print("url successfully reached")
            data = response.content
            with open(filename, "wb") as f:
                f.write(data)
                print(f"Data successfully writen in {filename}")
    except Exception as e:
        print("Error:", e)

In [23]:
url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/airline_data.csv'
filename = "airline_data.csv"

In [24]:
download(url, filename)

url successfully reached
Data successfully writen in airline_data.csv

In [25]:
df = pd.read_csv(filename)
df.head()

,Unnamed: 0,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,Origin,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,Dest,DestCityName,DestState,DestStateFips,DestStateName,DestWac,CRSDepTime,DepTime,DepDelay,DepDelayMinutes,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrTime,ArrDelay,ArrDelayMinutes,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,Cancelled,CancellationCode,Diverted,CRSElapsedTime,ActualElapsedTime,AirTime,Flights,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,FirstDepTime,TotalAddGTime,LongestAddGTime,DivAirportLandings,DivReachedDest,DivActualElapsedTime,DivArrDelay,DivDistance,Div1Airport,Div1AirportID,Div1AirportSeqID,Div1WheelsOn,Div1TotalGTime,Div1LongestGTime,Div1WheelsOff,Div1TailNum,Div2Airport,Div2AirportID,Div2AirportSeqID,Div2WheelsOn,Div2TotalGTime,Div2LongestGTime,Div2WheelsOff,Div2TailNum,Div3Airport,Div3AirportID,Div3AirportSeqID,Div3WheelsOn,Div3TotalGTime,Div3LongestGTime,Div3WheelsOff,Div3TailNum,Div4Airport,Div4AirportID,Div4AirportSeqID,Div4WheelsOn,Div4TotalGTime,Div4LongestGTime,Div4WheelsOff,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum
0,1295781,1998,2,4,2,4,1998-04-02,AS,19930,AS,N785AS,584,11884,1188401,31884,GEG,"Spokane, WA",WA,53.0,Washington,93,14747,1474702,30559,SEA,"Seattle, WA",WA,53.0,Washington,93,1330,1330.0,0.0,0.0,0.0,0.0,1300-1359,8.0,1338.0,1415.0,5.0,1426,1420.0,-6.0,0.0,0.0,-1.0,1400-1459,0.0,NaN,0.0,56.0,50.0,37.0,1.0,224.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1125375,2013,2,5,13,1,2013-05-13,EV,20366,EV,N24103,4132,11618,1161802,31703,EWR,"Newark, NJ",NJ,34.0,New Jersey,21,14524,1452401,34524,RIC,"Richmond, VA",VA,51.0,Virginia,38,1301,1255.0,-6.0,0.0,0.0,-1.0,1300-1359,9.0,1304.0,1358.0,13.0,1423,1411.0,-12.0,0.0,0.0,-1.0,1400-1459,0.0,NaN,0.0,82.0,76.0,54.0,1.0,277.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,118824,1993,3,9,25,6,1993-09-25,UA,19977,UA,NaN,2206,14108,1410801,34108,PIA,"Peoria, IL",IL,17.0,Illinois,41,13930,1393001,30977,ORD,"Chicago, IL",IL,17.0,Illinois,41,1650,1723.0,33.0,33.0,1.0,2.0,1600-1659,NaN,NaN,NaN,NaN,1730,1815.0,45.0,45.0,1.0,3.0,1700-1759,0.0,NaN,0.0,40.0,52.0,NaN,1.0,130.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,634825,1994,4,11,12,6,1994-11-12,HP,19991,HP,NaN,1207,12892,1289201,32575,LAX,"Los Angeles, CA",CA,6.0,California,91,14107,1410701,30466,PHX,"Phoenix, AZ",AZ,4.0,Arizona,81,1245,1309.0,24.0,24.0,1.0,1.0,1200-1259,NaN,NaN,NaN,NaN,1457,1538.0,41.0,41.0,1.0,2.0,1400-1459,0.0,NaN,0.0,72.0,89.0,NaN,1.0,370.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1888125,2017,3,8,17,4,2017-08-17,UA,19977,UA,N827UA,576,11003,1100303,31003,CID,"Cedar Rapids/Iowa City, IA",IA,19.0,Iowa,61,11292,1129202,30325,DEN,"Denver, CO",CO,8.0,Colorado,82,755,746.0,-9.0,0.0,0.0,-1.0,0700-0759,8.0,754.0,836.0,8.0,902,844.0,-18.0,0.0,0.0,-2.0,0900-0959,0.0,NaN,0.0,127.0,118.0,102.0,1.0,692.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df.shape

(27000, 110)

df.info(show_counts = True, verbose = True)

<h2>Scatter Plot of Ditance Vs Departure Time</h2>

In [9]:
fig = go.Figure()
fig.add_trace(go.Scatter(x = df["Distance"], y = df["DepTime"], mode = "markers", marker = dict(color = "red")))
fig.update_layout(title = "Distance VS Departure Time", xaxis_title = "Distance", yaxis_title = "Departure time")
#fig.show()

<class 'NameError'>: name 'go' is not defined

<h2>Line Plot monthly arrival delay time change over 12 Months </h2>

In [28]:
df_delay = df.groupby(by = "Month")["ArrDelay"].mean().reset_index()
df_delay.head()

   Month  ArrDelay
0      1  7.097321
1      2  6.530025
2      3  5.429533
3      4  4.040055
4      5  5.874889

In [10]:
fig = go.Figure()
fig.add_trace(go.Scatter(x = df_delay["Month"], y = df_delay["ArrDelay"], mode = "lines", marker = dict(color = "green")))
fig.update_layout(title= "Average Departure Delay over 12 Months", xaxis_title = "Months", yaxis_title = "Average departure delay")
#fig.show()

<class 'NameError'>: name 'go' is not defined

<h2>Bar Chart of Number of Flights per Destination</h2>

In [30]:
df_destination = df.groupby(by = "DestState")["Flights"].sum().reset_index()
df_destination.head()

  DestState  Flights
0        AK    192.0
1        AL    163.0
2        AR    118.0
3        AZ    842.0
4        CA   3174.0

In [11]:
fig = px.bar(df_destination, x = "DestState", y = "Flights", title = "NUmber of flights to specific destinations")
#fig.show()

<class 'NameError'>: name 'px' is not defined

<h2>Histogram: Distribution of Arrival Delay</h2>

In [32]:
df_arrDelay = df["ArrDelay"].fillna(0)
df_arrDelay[:5]

0    -6.0
1   -12.0
2    45.0
3    41.0
4   -18.0
Name: ArrDelay, dtype: float64

In [12]:
fig = px.histogram(df_arrDelay, x = "ArrDelay", title = "Distribution of Arrival Delay Time")
#fig.show()

<class 'NameError'>: name 'px' is not defined

<h2>Bubble Chart of Number of Flights by Airline</h2>

In [34]:
df_bubble = df.groupby(by = "Reporting_Airline")["Flights"].sum().reset_index()
df_bubble.head()

  Reporting_Airline  Flights
0                9E    262.0
1                AA   3151.0
2                AS    710.0
3                B6    499.0
4                CO   1208.0

In [13]:
fig = px.scatter(df_bubble, x = "Reporting_Airline", y = "Flights", size = "Flights", hover_name= "Reporting_Airline", size_max = 50, title = "Number of Flights per Airline")
#fig.show()

<class 'NameError'>: name 'px' is not defined

<h2>Proportion of Flights per Distance</h2>

In [38]:
df_pie = df.groupby(by= "DistanceGroup")["Flights"].sum().reset_index()
df_pie.head()

   DistanceGroup  Flights
0              1   4507.0
1              2   7435.0
2              3   5294.0
3              4   3628.0
4              5   2286.0

In [14]:
fig = px.pie(df_pie, values = "Flights", names ="DistanceGroup", title = "Proportion of Flights per Distance Group")
#fig.show()

<class 'NameError'>: name 'px' is not defined

<h2>Radial Chart of the Number of Flights by Month and destination</h2>

In [50]:
df["DestStateName"].isna().sum()

7

In [54]:
(df["DestStateName"] == "").sum()

0

In [55]:
df_clean = df.dropna(subset = "DestStateName")

In [58]:
df_clean["DestStateName"].isna().sum()
df_clean.head()

,Unnamed: 0,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,Origin,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,Dest,DestCityName,DestState,DestStateFips,DestStateName,DestWac,CRSDepTime,DepTime,DepDelay,DepDelayMinutes,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrTime,ArrDelay,ArrDelayMinutes,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,Cancelled,CancellationCode,Diverted,CRSElapsedTime,ActualElapsedTime,AirTime,Flights,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,FirstDepTime,TotalAddGTime,LongestAddGTime,DivAirportLandings,DivReachedDest,DivActualElapsedTime,DivArrDelay,DivDistance,Div1Airport,Div1AirportID,Div1AirportSeqID,Div1WheelsOn,Div1TotalGTime,Div1LongestGTime,Div1WheelsOff,Div1TailNum,Div2Airport,Div2AirportID,Div2AirportSeqID,Div2WheelsOn,Div2TotalGTime,Div2LongestGTime,Div2WheelsOff,Div2TailNum,Div3Airport,Div3AirportID,Div3AirportSeqID,Div3WheelsOn,Div3TotalGTime,Div3LongestGTime,Div3WheelsOff,Div3TailNum,Div4Airport,Div4AirportID,Div4AirportSeqID,Div4WheelsOn,Div4TotalGTime,Div4LongestGTime,Div4WheelsOff,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum
0,1295781,1998,2,4,2,4,1998-04-02,AS,19930,AS,N785AS,584,11884,1188401,31884,GEG,"Spokane, WA",WA,53.0,Washington,93,14747,1474702,30559,SEA,"Seattle, WA",WA,53.0,Washington,93,1330,1330.0,0.0,0.0,0.0,0.0,1300-1359,8.0,1338.0,1415.0,5.0,1426,1420.0,-6.0,0.0,0.0,-1.0,1400-1459,0.0,NaN,0.0,56.0,50.0,37.0,1.0,224.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1125375,2013,2,5,13,1,2013-05-13,EV,20366,EV,N24103,4132,11618,1161802,31703,EWR,"Newark, NJ",NJ,34.0,New Jersey,21,14524,1452401,34524,RIC,"Richmond, VA",VA,51.0,Virginia,38,1301,1255.0,-6.0,0.0,0.0,-1.0,1300-1359,9.0,1304.0,1358.0,13.0,1423,1411.0,-12.0,0.0,0.0,-1.0,1400-1459,0.0,NaN,0.0,82.0,76.0,54.0,1.0,277.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,118824,1993,3,9,25,6,1993-09-25,UA,19977,UA,NaN,2206,14108,1410801,34108,PIA,"Peoria, IL",IL,17.0,Illinois,41,13930,1393001,30977,ORD,"Chicago, IL",IL,17.0,Illinois,41,1650,1723.0,33.0,33.0,1.0,2.0,1600-1659,NaN,NaN,NaN,NaN,1730,1815.0,45.0,45.0,1.0,3.0,1700-1759,0.0,NaN,0.0,40.0,52.0,NaN,1.0,130.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,634825,1994,4,11,12,6,1994-11-12,HP,19991,HP,NaN,1207,12892,1289201,32575,LAX,"Los Angeles, CA",CA,6.0,California,91,14107,1410701,30466,PHX,"Phoenix, AZ",AZ,4.0,Arizona,81,1245,1309.0,24.0,24.0,1.0,1.0,1200-1259,NaN,NaN,NaN,NaN,1457,1538.0,41.0,41.0,1.0,2.0,1400-1459,0.0,NaN,0.0,72.0,89.0,NaN,1.0,370.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1888125,2017,3,8,17,4,2017-08-17,UA,19977,UA,N827UA,576,11003,1100303,31003,CID,"Cedar Rapids/Iowa City, IA",IA,19.0,Iowa,61,11292,1129202,30325,DEN,"Denver, CO",CO,8.0,Colorado,82,755,746.0,-9.0,0.0,0.0,-1.0,0700-0759,8.0,754.0,836.0,8.0,902,844.0,-18.0,0.0,0.0,-2.0,0900-0959,0.0,NaN,0.0,127.0,118.0,102.0,1.0,692.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
fig = px.sunburst(df_clean, path = ["Month", "DestStateName"], values = "Flights", title = "Hierarchical Representation of Flights by Month and Destination")
fig.update_layout(width = 900, height = 900)
#fig.show()

<class 'NameError'>: name 'px' is not defined