In [1]:
import pandas as pd
from scipy.stats import chi2_contingency
import numpy as np

<ipython-input-1-794ba72a4b20>:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
data_male = {"like":20,
             "dislike": 30}
data_femelle = {"like" : 25,
                "dislike" : 25}

In [3]:
data = np.array([
                [data_male["like"],data_male["dislike"]],
                [data_femelle["like"], data_femelle["dislike"]]
                ])

In [4]:
data

array([[20, 30],
       [25, 25]])

In [12]:
df = pd.DataFrame(data, columns = ["Like", "Dislike"], index = ["male", "femelle"])
df

         Like  Dislike
male       20       30
femelle    25       25

In [15]:
from IPython.display import display, HTML
chi, p, dof, expected = chi2_contingency(df)
df = pd.DataFrame(expected, index = ["male", "femelle"], columns = ["like", "dislike"])
display(HTML(f"""
        <h3>Chi-Square Test of Independence</h3>
        <ul style="list-style-type:none;">
        <li> Chi_square : {chi} </li>
        <li> Degree of freedom : {dof} </li>
        <li> p-value : {p} </li>
        <br>
        {df.to_html(index = True)}
        <br>
        <b>result</b> : χ²({dof}) = {chi:.2f}, <i>p</i> = {p:.2f}"""
))